config/routes.rb
Rails.application.routes.draw do

    root 'servers#index'

    resources :applications do
      member do
        get 'deploy'
      end
    end
    
    resources :servers do
      collection do
        get 'restart'
        get 'show_restart'
        get 'rebuild_tunnels'
        get 'show_rebuild_tunnels'
        get 'console_log'
        get 'show_console_log'
      end
    end

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :server

  def url
    "http://#{server.ip}:#{server.port}#{self.path}"
  end

  def package_name
    case self.application_type
    when 'WA'
      return 'Ativacao.ear'
    when 'WM'
      return 'ClaroAtivacao.ear'
    when 'WV'
      return 'WebVendas.war'
    when 'WADMIN'
      return 'ClaroAdministrador.ear'
    end
  end

  def deployed_name
    case self.application_type
    when 'WA'
      return "Ativacao"
    when 'WM'
      return "ClaroAtivacao"
    when 'WV'
      return "WebVendas"
    when 'WADMIN'
      return "ClaroAdministrador"
    end
  end

end

app/models/server.rb
class Server < ActiveRecord::Base
  has_many :applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  include ActionController::Live
  before_action :set_application, only: [:show, :deploy, :edit, :update]

  # GET /applications/1/edit
  def edit
  end

  def show
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    uploaded_io = params[:application][:package]

    dest = File.dirname(Rails.root.join('public', 'deployments', "#{@application.id}", uploaded_io.original_filename))
    unless File.directory?(dest)
      FileUtils.mkdir_p(dest)
    end
    File.open(File.join(dest, uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end

    @application.package = uploaded_io.original_filename
    @application.project = params[:application][:project]

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def deploy
    response.headers['Content-Type'] = 'text/event-stream'

    domain_home = "/opt/www/claro/#{@application.server.name.downcase}"
    deployments_root = "#{domain_home}/packages"

    from = Rails.root.join('public', 'deployments', "#{@application.id}", @application.package)
    to = File.join(deployments_root, @application.package_name)
    response.stream.write "Copying file #{from} to #{to}...\n"
    FileUtils.cp from, to
    response.stream.write "Done\n"

    script = Rails.root.join('bin', 'redeploy.py')

    url = "t3://#{@application.server.ip}:#{@application.server.port}"

    cmd = %(export MW_HOME=/opt/weblogic12; . $MW_HOME/wlserver/server/bin/setWLSEnv.sh; java weblogic.WLST #{script} #{@application.deployed_name} #{domain_home} #{url} 2>&1)

    response.stream.write "\n\nExecuting: #{cmd}\n\n"
  
    IO.popen(cmd).each do |line|
      #"Application with status completed"
      response.stream.write line
    end.close 

  ensure
    response.stream.close
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params[:application].permit(:package, :project)
    end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  def index
    @servers = Server.all
  end
  
  def restart
    response.headers['Content-Type'] = 'text/event-stream'
    cmd = "sudo service weblogic-qa restart 2>&1"
    response.stream.write "\n\nExecuting: #{cmd}\n\n"
    #IO.popen("chuta 2>&1").each do |line|
    IO.popen(cmd).each do |line|
      #"Application with status completed"
      response.stream.write line
    end.close
    
    ensure
      response.stream.close
  end
  
  def show_restart
  end

  def rebuild_tunnels 
    response.headers['Content-Type'] = 'text/event-stream'
    
    cmd = "sudo service claro-tunnels restart 2>&1"
    response.stream.write "\n\nExecuting: #{cmd}\n\n"
    IO.popen(cmd).each do |line|
      #"Application with status completed"
      response.stream.write line
    end.close
    
    ensure
      response.stream.close
  end

  def show_rebuild_tunnels
  end

  def console_log 
    response.headers['Content-Type'] = 'text/event-stream'
    
    cmd = "tail -f /var/log/qa/STDOUT.log"
    response.stream.write "\n\nExecuting: #{cmd}\n\n"
    IO.popen(cmd).each do |line|
      #"Application with status completed"
      response.stream.write line
    end.close
    
    ensure
      response.stream.close
  end

  def show_console_log
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/server_helper.rb
module ServerHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Applications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<div class="row">
<div class="col-md-12">
<h1>Executando deploy de "<%=@application.name%>" do projeto "<%=@application.project%>" em <%=@application.server.name.upcase%></h1>

<br/>

<iframe src="<%=deploy_application_path(@application)%>" width="100%" height="550" id="console-output"></iframe>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Dublin</title>
<%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
<%# javascript_include_tag 'application', 'data-turbolinks-track' => false %>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>
</head>
<body>

<div class="container">
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="<%=root_path%>"><span><%= image_tag "claro.png", width: 30, height: 30 %></span> QA Claro/Vendas (SysMap)</a>
</div>
<div id="navbar" class="navbar-collapse collapse">
<ul class="nav navbar-nav navbar-right">
<li><a href="http://www.cvv.org.br" target="_blank">Ajuda</a></li>
</ul>
</div>
</div>
</nav>
</div>

<div class="container" style="padding-top: 70px;">
<%= yield %>
</div>

</body>
</html>

app/views/servers/index.html.erb
<div class="row">
<div class="col-md-12">
<h1>Servidores de QA da fábrica</h1>
<table class="table">
<tr><td colspan="6" align="right"><%= link_to 'Console Log', show_console_log_servers_path, class: 'btn btn-primary', disabled: 'disabled' %>&nbsp;<%= link_to 'Refazer Túneis', show_rebuild_tunnels_servers_path, class: 'btn btn-warning', disabled: 'disabled' %>&nbsp;<%= link_to 'Reiniciar Servidor', show_restart_servers_path, class: 'btn btn-danger' %></td></tr>
<% @servers.each do |server| %>
<tr><td colspan="6"><h2><%=server.name%></h2></td></tr>
<% server.applications.each do |app| %>
<tr>
 <td><%=app.application_type%></td>
 <td><%=app.name%></td>
 <td><%=app.project%></td>
 <td><a href="<%=app.url%>" target="_blank"><%=app.url%></a></td>
 <td><%=app.package%></td>
 <td><button type="button" class="btn btn-primary new-deploy" data-target="<%=app.id%>">Novo Deploy</button>
</tr>
<tr class="form-deploy" id="tr-<%=app.id%>" style="display:none;">
 <td colspan="6">
  <%= form_for app, html: {class: 'form-inline'} do |f| %>
    <div class="form-group">
    <label>Projeto</label>
    <%= f.text_field :project, class: 'form-control' %>
    </div>
    <label>Pacote</label>
    <div class="form-group">
    <%= f.file_field :package, class: 'form-control' %>
    </div>
    <%= f.submit "Deploy", class: 'btn btn-danger' %>
  <% end %>
 </td>
</tr>
<% end %>

<% end %>
</table>
</div>
</div>

app/views/servers/show_console_log.html.erb
<div class="row">
<div class="col-md-12">
<h1>Console Log</h1>

<br/>

<iframe src="<%=console_log_servers_path%>" width="100%" height="550" id="console-output"></iframe>
</div>
</div>

app/views/servers/show_rebuild_tunnels.html.erb
<div class="row">
<div class="col-md-12">
<h1>Refazendo túneis</h1>

<br/>

<iframe src="<%=rebuild_tunnels_servers_path%>" width="100%" height="550" id="console-output"></iframe>
</div>
</div>

app/views/servers/show_restart.html.erb
<div class="row">
<div class="col-md-12">
<h1>Reiniciando servidor</h1>

<br/>

<iframe src="<%=restart_servers_path%>" width="100%" height="550" id="console-output"></iframe>
</div>
</div>